---
# Global section defines some global parameters
global:
  # autorization (string): [true/false]
  # Defines that the clients must be work with token or not. If set "true" you have to define users section
  authorization: "false"
  # master (string): [true/false]
  # Defines that this server has some slaves. If set "true" you have to define slaves section
  master: "true"

# Slave section 
slaves:
  - slave:
    id : 1
    ip : "127.0.0.1"
    port : "2324"
    authorization: "false"
    token: "061b30a7-1a12-4280-8e3c-6bc9a19b1683"
  - slave:
    id : 2
    ip : "127.0.0.1"
    port : "2325"
    authorization: "false"
    token: "061b30a7-1a12-4280-8e3c-6bc9a19b1683"
   
proc:
  cores: 8
  threads: 4

listen:
  ip: "0.0.0.0"
  port: "2323"
  protocol: "tcp"

log:
  level: 1
  path: "/tmp/nipo.log"

users:
  - user:
    name: "admin"
    token: "061b30a7-1a12-4280-8e3c-6bc9a19b1683"
    keys: ".*"
    cmds: "all"
  - user:
    name: "readonly"
    token: "0517376d-49c1-40eb-a8fc-fd73b70a4ce9"
    keys: "name.*||.*log.*"
    cmds: "get||select||avg"