---
listen:
  ip: "0.0.0.0"
  port: "2323"
  protocol: "tcp"

log:
  level: 1
  path: "/tmp/nipo.log"

users:
  - user:
    username: "admin"
    password: "admin"
    keys: ".*"
    cmds: "all"
  - user:
    username: "readonly"
    password: "readonly"
    keys: "name.*||.*log.*"
    cmds: "get||select||avg"