---
  
listen:
  ip: "0.0.0.0"
  port: "2323"
  protocol: "tcp"

log:
  level: "debug"
  path: "/tmp/nipo.log"

users:
  user:
    username: "admin"
    password: "admin"
    keys: ".*"
    cmds: "all"
  user:
    username: "morteza"
    password: "morteza"
    keys: ".*"
    cmds: "all"